language: node_js
node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - cd web
  - npm install
  - npm run build
  - npm test

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN