language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

script:
  - cd web-2
  - npm install
  - npm run test-ci

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
