language: node_js
node_js:
  - 12

script:
  - cd web-2
  - npm install
  - npm run test-ci
  - npm run build

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: development
