language: node_js
node_js:
  - 12

before_script:
  - npm i -g firebase-tools

script:
  - cd web
  - npm install
  - npm run test-ci
  - npm run build

deploy:
  - provider: script
    script: bash web/deploy_production.sh
    on:
      branch: master
  - provider: script
    script: bash web/deploy_dev.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ dev/[A-Za-z0-9]+
