language: node_js
node_js:
  - 12

before_script:
  - npm i -g firebase-tools

script:
  - cd web-2
  - npm install
  - npm run test-ci
  - npm run build

after_script:
  - firebase deploy --token "$FIREBASE_TOKEN"
